AWSTemplateFormatVersion: '2010-09-09'
Description: Transit Gateway setup for COSMOS-style multi-VPC environment

Resources:
  COSMOSTransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      Description: COSMOS Transit Gateway
      AmazonSideAsn: 64512
      AutoAcceptSharedAttachments: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      Tags:
        - Key: Name
          Value: COSMOS-TGW

Outputs:
  TransitGatewayId:
    Description: The ID of the Transit Gateway
    Value: !Ref COSMOSTransitGateway