AWSTemplateFormatVersion: '2010-09-09'
Description: VPC Core Infrastructure for GovCloud COSMOS Project

Parameters:
  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC

Resources:
  COSMOSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: COSMOS-VPC

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref COSMOSVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [ 0, !GetAZs "" ]
      Tags:
        - Key: Name
          Value: Public-Subnet-AZ1

Outputs:
  VPCId:
    Description: The ID of the created VPC
    Value: !Ref COSMOSVPC

  PublicSubnetId:
    Description: The ID of the public subnet
    Value: !Ref PublicSubnet